variables:
  REGISTRY_HOST: "dkhub.funceme.br:444"
  TAGNAME: "1.9.8"

stages:
  - build

build_image:
  stage: build
  image: docker:latest
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_HOST
    - docker build -t $REGISTRY_HOST/$CI_PROJECT_PATH:$TAGNAME .
    - docker push $REGISTRY_HOST/$CI_PROJECT_PATH:$TAGNAME
  only:
    - release-v1.9.8

